version: "3.9"

services:
  backend:
    build:
      dockerfile: ./Dockerfile
      context: ./
    image: healthdiarybackend
    container_name: healthdiarybackend
    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://postgres:root@db:5432/healthdiary
    command: python app/main.py
    ports:
      - "5050:8000"
    volumes:
      - .:/healthdiarybackend
    depends_on:
      db:
        condition: service_healthy  # Ждём, пока Postgres не станет "healthy"

  db:
    image: postgres:15.4
    container_name: healthdiarydb
    environment:
      POSTGRES_DB: healthdiary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
