services:
  backend:
    build:
      dockerfile: ./Dockerfile
      context: ./
    image: healthdiarybackend
    container_name: healthdiarybackend
    env_file:
      - app/.env
    environment:
      - RUNNING_IN_DOCKER=1
    command: python app/main.py
    ports:
      - "80:8000"
    volumes:
      - .:/healthdiarybackend
    depends_on:
      db:
        condition: service_healthy  # Ждём, пока Postgres не станет "healthy"

  db:
    image: postgres:15.4
    container_name: healthdiarydb
    env_file:
      - app/.env
    environment:
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:9.8
    env_file:
      - app/.env
    ports:
      - "5050:80"

volumes:
  pgdata:
