"""create water_intakes table

Revision ID: dbae209d5edd
Revises: bf683416d322
Create Date: 2025-10-28 20:09:14.554831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbae209d5edd'
down_revision: Union[str, Sequence[str], None] = 'bf683416d322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_intakes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('intake_amount', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('intake_amount >= 0', name=op.f('ck_water_intakes_check_positive_intake_amount')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_water_intakes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_water_intakes')),
    sa.UniqueConstraint('guid', name=op.f('uq_water_intakes_guid')),
    sa.UniqueConstraint('user_id', 'record_date', name='uq_water_intakes_user_id_record_date')
    )
    op.create_index(op.f('ix_water_intakes_record_date'), 'water_intakes', ['record_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_water_intakes_record_date'), table_name='water_intakes')
    op.drop_table('water_intakes')
    # ### end Alembic commands ###
