"""create activities table

Revision ID: bf683416d322
Revises: 0fc92a005f39
Create Date: 2025-10-24 22:48:14.281713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf683416d322'
down_revision: Union[str, Sequence[str], None] = '0fc92a005f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('calories', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('rest_hours', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('distance_km', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('calories >= 0', name=op.f('ck_activities_check_positive_calories')),
    sa.CheckConstraint('distance_km >= 0', name=op.f('ck_activities_check_positive_distance_km')),
    sa.CheckConstraint('rest_hours >= 0', name=op.f('ck_activities_check_positive_rest_hours')),
    sa.CheckConstraint('steps >= 0', name=op.f('ck_activities_check_positive_steps')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities')),
    sa.UniqueConstraint('guid', name=op.f('uq_activities_guid')),
    sa.UniqueConstraint('user_id', 'record_date', name='uq_activities_user_id_record_date')
    )
    op.create_index(op.f('ix_activities_record_date'), 'activities', ['record_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_record_date'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
