"""create drugs table

Revision ID: 7190fa240483
Revises: efc1c9d23918
Create Date: 2025-10-07 22:14:33.199204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7190fa240483'
down_revision: Union[str, Sequence[str], None] = 'efc1c9d23918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drugs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.Float(), nullable=False),
    sa.Column('dosage_unit', sa.Enum('MILLIGRAM', 'MILLILITER', name='dosageunitenum'), nullable=False),
    sa.Column('dosage_type', sa.Enum('CAPSULE', 'PILL', 'POWDER', name='dosagetypeenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drugs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drugs')
    # ### end Alembic commands ###
